CREATE DATABASE IF NOT EXISTS repolens
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'repolens'@'%' IDENTIFIED BY 'repolens123';
GRANT ALL PRIVILEGES ON repolens.* TO 'repolens'@'%';
FLUSH PRIVILEGES;
